# Generated by Django 4.2.5 on 2023-10-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftproduct',
            name='artwork',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nftproduct',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='generic/default_avatar.svg', upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creator',
            field=models.BooleanField(default=False),
        ),
    ]
