# Generated by Django 4.2.5 on 2023-10-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_04_3840x2400', upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
