# Generated by Django 4.2.5 on 2023-10-27 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_02_3840x2400.jpg', upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='voteblogcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_voted_by', to='NFTapp.blogcomment'),
        ),
        migrations.AlterField(
            model_name='voteproductcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment_voted_by', to='NFTapp.productcomment'),
        ),
    ]
