# Generated by Django 4.2.5 on 2023-11-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_01_3840x2400.jpg', upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='property',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
