# Generated by Django 4.2.5 on 2023-10-02 03:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0002_nftproduct_artwork_alter_nftproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nftproduct',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.fields.CharField>/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
