# Generated by Django 4.2.5 on 2023-11-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0002_alter_user_cover_photo_alter_user_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_02_3840x2400.jpg', upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='property',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
