# Generated by Django 4.2.5 on 2023-09-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='%Y/%m/%d/'),
        ),
    ]
