# Generated by Django 4.2.5 on 2023-09-24 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorNFTProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFTProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('descriptiton', models.TextField(null=True)),
                ('authors', models.ManyToManyField(through='NFTapp.AuthorNFTProduct', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerNFTProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NFTapp.nftproduct')),
            ],
        ),
        migrations.AddField(
            model_name='nftproduct',
            name='owners',
            field=models.ManyToManyField(related_name='owned_nft_products', through='NFTapp.OwnerNFTProduct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nftproduct',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NFTapp.topic'),
        ),
        migrations.AddField(
            model_name='authornftproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NFTapp.nftproduct'),
        ),
    ]
