# Generated by Django 4.2.5 on 2023-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default="{% static 'images/generic/default_avatar.svg' %}", upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
