# Generated by Django 4.2.5 on 2023-10-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0004_cart_alter_user_cover_photo_cartitem_cart_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_05_3840x2400.png', upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
