# Generated by Django 4.2.5 on 2023-10-30 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0004_rename_owner_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_03_3840x2400.jpg', upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='DisvoteProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment_disvoted_by', to='NFTapp.productcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disvotes_on_product_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
