# Generated by Django 4.2.5 on 2023-12-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0005_alter_user_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/images/avatar/avatar7.svg', upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_01_3840x2400.jpg', upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
