# Generated by Django 4.2.5 on 2023-10-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0005_alter_user_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_02_3840x2400.jpg', upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
