# Generated by Django 4.2.5 on 2023-10-30 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0005_alter_user_cover_photo_disvoteproductcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='disvotes',
            field=models.ManyToManyField(related_name='disvoted_product_comments', through='NFTapp.DisvoteProductComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_02_3840x2400.jpg', upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='DisvoteBlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_disvoted_by', to='NFTapp.blogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disvotes_on_blog_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='disvotes',
            field=models.ManyToManyField(related_name='disvoted_blog_comments', through='NFTapp.DisvoteBlogComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
