# Generated by Django 4.2.5 on 2023-11-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0006_productcomment_disvotes_alter_user_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='cart_products', through='NFTapp.CartItem', to='NFTapp.nftproduct'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_03_3840x2400.jpg', upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
