# Generated by Django 4.2.5 on 2023-10-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0006_nftblog_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftproduct',
            name='image',
            field=models.ImageField(upload_to='nft_product_images/%Y/%m/%d/'),
        ),
    ]
