# Generated by Django 4.2.5 on 2023-12-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0006_alter_user_avatar_alter_user_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
