# Generated by Django 4.2.5 on 2023-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0007_user_followers_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftproduct',
            old_name='type',
            new_name='type_product',
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_01_3840x2400.jpg', upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
