# Generated by Django 4.2.5 on 2023-10-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0007_alter_user_avatar_alter_user_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='property',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_03_3840x2400.jpg', upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
