# Generated by Django 4.2.5 on 2023-10-07 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0008_comment_blog_alter_blogimage_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/%Y/%m/%d/')),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='nftblog',
            name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nftblog',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.AddField(
            model_name='blogssection',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_image', to='NFTapp.nftblog'),
        ),
    ]
