# Generated by Django 4.2.5 on 2023-10-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0008_rename_type_nftproduct_type_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftproduct',
            name='type_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_type', to='NFTapp.type'),
        ),
    ]
