# Generated by Django 4.2.5 on 2023-10-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0009_blogssection_remove_nftblog_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogsSection',
            new_name='BlogSection',
        ),
    ]
