# Generated by Django 4.2.5 on 2023-10-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0010_rename_blogssection_blogsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='image',
            field=models.ImageField(null=True, upload_to='blog_images/%Y/%m/%d/'),
        ),
    ]
