# Generated by Django 4.2.5 on 2023-10-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0011_alter_blogsection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_section', to='NFTapp.nftblog'),
        ),
    ]
