# Generated by Django 4.2.5 on 2023-10-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0012_alter_blogsection_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='image',
            field=models.ImageField(null=True, upload_to='blog/%Y/%m/%d/'),
        ),
    ]
