# Generated by Django 4.2.5 on 2023-10-07 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0014_nftblog_image_alter_blogsection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftblog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
