# Generated by Django 4.2.5 on 2023-10-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0016_faqtitle_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='NFTapp.faqtitle'),
        ),
    ]
