# Generated by Django 4.2.5 on 2023-10-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTapp', '0017_alter_faq_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(default='/static/images/generic/Acer_Wallpaper_05_3840x2400', upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
